### ISSUE TITLE
:modm:docs is broken on Windows

### ISSUE THREAD

**Issue by fb39ca4** [modm-io/modm#121]
This first traceback happens when trying to read `{modm-repo}/tools/build_script_generator/module.md`
```
Traceback (most recent call last):
  File "C:\Users\fb39ca4\git\stm32f446-can-test\modm-repo\tools\doc_generator\module.lb", line 166, in post_build
    title, descr = split_description(m._description)
  File "C:\Users\fb39ca4\git\stm32f446-can-test\modm-repo\tools\doc_generator\module.lb", line 127, in split_description
    lines = str(descr).strip(" \n").splitlines() + [""]
  File "C:\Users\fb39ca4\AppData\Local\Programs\Python\Python37\lib\site-packages\lbuild\node.py", line 75, in __str__
    return self.read()
  File "C:\Users\fb39ca4\AppData\Local\Programs\Python\Python37\lib\site-packages\lbuild\node.py", line 78, in read
    return file.read()
  File "C:\Users\fb39ca4\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 3281: character maps to <undefined>
```

This traceback happens when trying to write `{output}/docs/dox/modm-build.dox`
```
Traceback (most recent call last):
  File "C:\Users\fb39ca4\git\stm32f446-can-test\modm-repo\tools\doc_generator\module.lb", line 196, in post_build
    env.template("group.dox.in", "{}.dox".format(url_name(m["name"])), filters={"doxify": doxify})
  File "C:\Users\fb39ca4\AppData\Local\Programs\Python\Python37\lib\site-packages\lbuild\facade.py", line 178, in template
    self._env.template(src, dest, substitutions, filters)
  File "C:\Users\fb39ca4\AppData\Local\Programs\Python\Python37\lib\site-packages\lbuild\environment.py", line 323, in template
    outfile.write(output)
  File "C:\Users\fb39ca4\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u250c' in position 3129: character maps to <undefined>
```

Adding `encoding="utf-8"` to the `open` calls in `node.py` and `environment.py` just before the exception happens makes the problem go away, but I'm not sure if you want to fix it on lbuild or modm's side.

Also, it would be nice for lbuild to better print stack traces, since by default they only show the most recent call with no further context. I had to insert some try-catch blocks in the code and print stack traces myself, but I will bring up that issue in the lbuild repo.

**Comment by salkinium** [comment]
Ah, Windows, my old nemesis…

> Adding `encoding="utf-8"` to the `open` calls in `node.py` and `environment.py`

Dang, I would've wanted pathlib to take care of that, but it's not the first encoding issue on Windows in lbuild. I think you will need to fix this in lbuild, not in modm.

> Also, it would be nice for lbuild to better print stack traces […] but I will bring up that issue in the lbuild repo.

Please do!

**Comment by fb39ca4** [comment]
Pathlib is only dealing with file paths not, contents, which is why you still have to worry about it.
